-- public.credentials definition

-- Drop table

-- DROP TABLE credentials;

CREATE TABLE credentials (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(100) NOT NULL,
	status bool NOT NULL,
	"password" varchar(255) NOT NULL,
	username varchar(50) NOT NULL,
	salt varchar(255) NULL DEFAULT NULL::character varying,
	created_by varchar(50) NULL,
	created_on timestamp NULL,
	created_host varchar(20) NULL,
	modified_by varchar(50) NULL,
	modified_on timestamp NULL,
	modified_host varchar(20) NULL,
	verification_code varchar NULL,
	public_user bool NULL,
	CONSTRAINT "PK_credentials" PRIMARY KEY (id)
);