-- public.menu_role_map definition

-- Drop table

-- DROP TABLE menu_role_map;

CREATE TABLE menu_role_map (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	menu_id int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT "PK_menu_role_map" PRIMARY KEY (id)
);
CREATE INDEX "IX_menu_role_map_menu_id" ON public.menu_role_map USING btree (menu_id);
CREATE INDEX "IX_menu_role_map_role_id" ON public.menu_role_map USING btree (role_id);


-- public.menu_role_map foreign keys

ALTER TABLE public.menu_role_map ADD CONSTRAINT menu_role_map_fk FOREIGN KEY (menu_id) REFERENCES menu(id) ON DELETE RESTRICT;
ALTER TABLE public.menu_role_map ADD CONSTRAINT menu_role_map_fk_1 FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE RESTRICT;