-- public.role_map definition

-- Drop table

-- DROP TABLE role_map;

CREATE TABLE role_map (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	role_id int8 NOT NULL,
	credential_id int8 NOT NULL,
	CONSTRAINT "PK_role_map" PRIMARY KEY (id)
);
CREATE INDEX "IX_role_map_credential_id" ON public.role_map USING btree (credential_id);
CREATE INDEX "IX_role_map_role_id" ON public.role_map USING btree (role_id);


-- public.role_map foreign keys

ALTER TABLE public.role_map ADD CONSTRAINT role_map_credentials_fk FOREIGN KEY (credential_id) REFERENCES credentials(id) ON DELETE RESTRICT;
ALTER TABLE public.role_map ADD CONSTRAINT role_map_role_fk FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE RESTRICT;