-- public."role" definition

-- Drop table

-- DROP TABLE "role";

CREATE TABLE "role" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(50) NOT NULL,
	status bool NOT NULL,
	CONSTRAINT "PK_role" PRIMARY KEY (id)
);