-- public."user" definition

-- Drop table

-- DROP TABLE "user";

CREATE TABLE "user" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	credential_id int8 NOT NULL,
	first_name varchar(50) NULL,
	last_name varchar(50) NULL,
	phone varchar NULL,
	created_by varchar(50) NULL,
	created_on timestamp NULL,
	created_host varchar(20) NULL,
	modified_by varchar(50) NULL,
	modified_on timestamp NULL,
	modified_host varchar(20) NULL,
	CONSTRAINT "PK_user" PRIMARY KEY (id)
);
CREATE INDEX "IX_user_credential_id" ON public."user" USING btree (credential_id);


-- public."user" foreign keys

ALTER TABLE public."user" ADD CONSTRAINT user_fk FOREIGN KEY (credential_id) REFERENCES credentials(id) ON DELETE RESTRICT;